SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091 -- generated by uv during the recipe build.
source "$SCRIPT_DIR/.venv/bin/activate"
export PATH="$VIRTUAL_ENV/bin:$SCRIPT_DIR/data/external/bin:${PATH#"$VIRTUAL_ENV/bin:"}"
# Ray workers can inherit an image cuDNN before its search path is consulted. Preload the
# recipe-installed runtime selected with subquadratic-ops, while keeping repeated sourcing safe.
for cudnn_library in "$VIRTUAL_ENV"/lib/python*/site-packages/nvidia/cudnn/lib/libcudnn.so.9; do
  if [ -f "$cudnn_library" ]; then
    cudnn_directory="${cudnn_library%/*}"
    case ":${LD_LIBRARY_PATH:-}:" in
      *":$cudnn_directory:"*) ;;
      *) export LD_LIBRARY_PATH="$cudnn_directory${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" ;;
    esac
    case ":${LD_PRELOAD:-}:" in
      *":$cudnn_library:"*) ;;
      *) export LD_PRELOAD="$cudnn_library${LD_PRELOAD:+:$LD_PRELOAD}" ;;
    esac
    break
  fi
done
checkv_db=""
for candidate in "$SCRIPT_DIR"/data/external/checkv/checkv-db-*; do
  if [ -d "$candidate" ]; then
    checkv_db="$candidate"
  fi
done
if [ -n "$checkv_db" ]; then
  export CHECKVDB="$checkv_db"
fi
