SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091 -- generated by uv during the recipe build.
source "$SCRIPT_DIR/.venv/bin/activate"
export PATH="$VIRTUAL_ENV/bin:$SCRIPT_DIR/data/external/bin:${PATH#"$VIRTUAL_ENV/bin:"}"
checkv_db=""
for candidate in "$SCRIPT_DIR"/data/external/checkv/checkv-db-*; do
  if [ -d "$candidate" ]; then
    checkv_db="$candidate"
  fi
done
if [ -n "$checkv_db" ]; then
  export CHECKVDB="$checkv_db"
fi
