SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091 -- generated by uv during the recipe build.
source "$SCRIPT_DIR/.venv/bin/activate"
export PATH="$VIRTUAL_ENV/bin:$SCRIPT_DIR/data/external/bin:${PATH#"$VIRTUAL_ENV/bin:"}"
# Prefer the cuDNN runtime installed with subquadratic-ops over an older image copy.
for candidate in "$VIRTUAL_ENV"/lib/python*/site-packages/nvidia/cudnn/lib; do
  if [ -d "$candidate" ]; then
    export LD_LIBRARY_PATH="$candidate${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    break
  fi
done
checkv_db=""
for candidate in "$SCRIPT_DIR"/data/external/checkv/checkv-db-*; do
  if [ -d "$candidate" ]; then
    checkv_db="$candidate"
  fi
done
if [ -n "$checkv_db" ]; then
  export CHECKVDB="$checkv_db"
fi
